[package]
name = "cublasxt"
version = "0.1.0"
authors = ["Michal Sudwoj <msudwoj@student.ethz.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cublasxt-sys = { path = "cublasxt-sys" }
num-complex = "*"
